Sprint 9 solution http api
GritsED/java-kanban pull request #4
Opened 2024-12-22 14:45 UTC by GritsED

Реализовал 9 спринт

Привет,

Жду правки и можешь еще глянуть по рефакторингу, на какие моменты обратить внимание, чтобы лучше стало? =-)

2024-12-23 08:22 UTC, vlolad requested changes
Привет!

Хорошая работа, багов не обнаружил, только улучшения по коду
Есть замечание по наследованию хендлеров - все должны наследоваться только от базовой реализации, все общеиспользуемые методы/поля тоже надо туда перенести. Комментарии написал в EpicHandler

В остальном критичных замечаний нет, так что дорабатываем и уходим в новый год)
Хорошего дня!

2024-12-23 08:22 UTC, vlolad commented on src/server/HttpTaskServer.java
> +        httpServer.createContext("/prioritized", new PrioritizedHandler(manager));
Хорошо, что на каждый тип задачи свои хендлеры сделал

2024-12-23 08:22 UTC, vlolad commented on src/server/handlers/EpicHandler.java
> +public class EpicHandler extends TaskHandler {
Не-не, это не так работает)
Тут стратегия наследования моделей неприменима, все хендлеры наследуем от BaseHttpHandler
Если какие-то общие методы используются, вроде getId, их можно вынести туда же в родительский класс

2024-12-23 08:22 UTC, vlolad commented on src/server/handlers/EpicHandler.java
> +    private final Gson gson = new GsonBuilder().serializeNulls().registerTypeAdapter(Duration.class, new DurationAdapter())
Gson можно вынести в BaseHandler и сделать protected, так у всех дочерних классов доступ сразу будет

2024-12-23 19:24 UTC, GritsED commented
Привет

Обновил классы
Вынес общие переменные и изменил наследование

Вопрос по методам handleGet Post и др. Мне кажется, что они слишком уж больше вышли, стоит ли их разбивать на более мелкие?

2024-12-24 11:36 UTC, vlolad approved these changes
Привет!

Упрощать, конечно, можно, но у тебя одна из самых лаконичных реализаций, так что все ок. В коробочных Java-решениях подобные хендлеры могут быть и по 500+ строк, так что молодец)

Ещё в некоторых работах бывает, что все хендлеры в один метод умещают. Вот это было бы плохо
Один комментарий по рефакторингу оставил (по просьбе трудящихся с: ), но работа принята т.к. полностью соответствует ТЗ

С наступающим!

2024-12-24 11:36 UTC, vlolad commented on src/server/handlers/EpicHandler.java
> +            if (pathParts.length == 2 && pathParts[1].equals("epics")) {
Тут можно было бы оставить условие `pathParts.length == 2`, но обернуть в switch, а наличие "epics" проверять перед этим

Просто в качестве рефакторинга

2024-12-27 11:20 UTC, merged